version: "3.3"

services:
  backend:
    build: .
    container_name: vle-api
    command: uvicorn --reload --host=${SERVER_HOST} --port=${SERVER_PORT} app.main:app
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: vle-db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  db-data:
