version: "3.3"

services:
  backend:
    container_name: vle-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../.:/app
    restart: always
