version: "3.3"

services:
  backend:
    container_name: vle-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../.:/app
    restart: always
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: vle-db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - 5432:5432

volumes:
  db-data:
