"""change ondelete fk event for discipline

Revision ID: 3cb9ee492022
Revises: d4c1f2ae2a16
Create Date: 2023-01-29 13:39:07.560881

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "3cb9ee492022"
down_revision = "d4c1f2ae2a16"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("discipline_plan_fkey", "discipline", type_="foreignkey")
    op.create_foreign_key(
        None, "discipline", "file", ["plan"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "discipline", type_="foreignkey")
    op.create_foreign_key(
        "discipline_plan_fkey",
        "discipline",
        "file",
        ["plan"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
