"""create file_theme table

Revision ID: 3d8f84d47c73
Revises: c83956143830
Create Date: 2023-01-15 13:04:58.322136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3d8f84d47c73"
down_revision = "c83956143830"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filetheme",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("file_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("theme_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(["file_id"], ["file.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["theme_id"], ["theme.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("filetheme")
    # ### end Alembic commands ###
