"""create discipline_specialty table

Revision ID: 51585717d351
Revises: 769baa5cd551
Create Date: 2022-10-16 19:40:49.470979

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "51585717d351"
down_revision = "769baa5cd551"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disciplinespecialty",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("discipline_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("specialty_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["discipline_id"], ["discipline.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["specialty_id"], ["specialty.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("disciplinespecialty")
    # ### end Alembic commands ###
