"""add role name attr

Revision ID: 5a08300b8f7c
Revises: 6217e889bebc
Create Date: 2022-10-02 16:15:31.558950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5a08300b8f7c"
down_revision = "6217e889bebc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("role", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("role", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
