"""add unique attr for file url

Revision ID: 79cfbace475a
Revises: cf0e5773b4f7
Create Date: 2022-10-14 11:19:24.264461

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "79cfbace475a"
down_revision = "cf0e5773b4f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "file", ["url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file", type_="unique")  # type: ignore
    # ### end Alembic commands ###
