"""add plan for discipline

Revision ID: c83956143830
Revises: 6e0c011647df
Create Date: 2022-10-17 15:42:53.101228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c83956143830"
down_revision = "6e0c011647df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "discipline", sa.Column("plan", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(
        None, "discipline", "file", ["plan"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "discipline", type_="foreignkey")
    op.drop_column("discipline", "plan")
    # ### end Alembic commands ###
