"""add file name

Revision ID: cd1ad9946317
Revises: 3d8f84d47c73
Create Date: 2023-01-28 09:22:27.873676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1ad9946317'
down_revision = '3d8f84d47c73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'name')
    # ### end Alembic commands ###
