name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dev-dependencies
        run: |
          pip install mypy==0.971
          pip install flake8==5.0.4
          pip install pydantic==1.10.2
          pip install sqlalchemy-stubs==0.4
        shell: bash

      - name: Lint
        run: |
          flake8 app
          mypy app
        shell: bash
