name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dev-dependencies
        run: |
          pip install flake8==5.0.4
          pip install greenlet==1.1.3
          pip install mccabe==0.7.0
          pip install mypy==0.971
          pip install mypy-extensions==0.4.3
          pip install pycodestyle==2.9.1
          pip install pydantic==1.10.2
          pip install pyflakes==2.5.0
          pip install SQLAlchemy==1.4.41
          pip install sqlalchemy2-stubs==0.0.2a27
          pip install tomli==2.0.1
          pip install typing_extensions==4.3.0
        shell: bash

      - name: Lint
        run: |
          flake8 app
          mypy app
        shell: bash
